import type { Profile } from './supabase'

/**
 * Demo student used when Supabase is not connected, so the student profile can
 * be accessed offline. This never runs when real Supabase keys are present.
 */
export const DEMO_STUDENT: Profile = {
  id: 'demo-student-chielsea',
  role: 'student',
  email: 'chielsea.napoles@cit.edu',
  full_name: 'Chielsea S. Napoles',
  first_name: 'Chielsea',
  middle_initial: 'S',
  last_name: 'Napoles',
  suffix: null,
  course: 'BS Computer Science',
  year_level: '3rd Year',
  university: 'Cebu Institute of Technology – University',
  age: null,
  gender: null,
  address: null,
  personal_email: null,
  contact_number: null,
  photo_url: null,
  skills: ['React', 'TypeScript', 'Node.js', 'Figma'],
  specializations: ['Frontend Development', 'UI/UX Design'],
  ai_skills: ['React', 'TypeScript'],
  ai_specializations: ['Frontend Development'],
  resume_url: 'chielsea_resume.pdf',
  resume_status: 'analyzed',
  resume_analyzed_at: new Date().toISOString(),
  resume_ai_suggestion: null,
  portfolio_link: 'https://chielsea-portfolio.dev',
  portfolio_file_url: null,
  profile_completed: true,
  is_active: true,
  deactivation_reason: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

/**
 * Demo admin for temporary offline access to the admin portal.
 * In the real backend, admins are seeded manually (never self-registered).
 */
/** Demo company representative for offline access to the company portal. */
export const DEMO_COMPANY: Profile = {
  id: 'demo-company-arcway',
  role: 'company',
  email: 'hr@arcwaylabs.com',
  full_name: 'Arcway Labs',
  first_name: null,
  middle_initial: null,
  last_name: null,
  suffix: null,
  course: null,
  year_level: null,
  university: null,
  age: null,
  gender: null,
  address: null,
  personal_email: null,
  contact_number: null,
  photo_url: null,
  skills: [],
  specializations: [],
  ai_skills: [],
  ai_specializations: [],
  resume_url: null,
  resume_status: null,
  resume_analyzed_at: null,
  resume_ai_suggestion: null,
  portfolio_link: null,
  portfolio_file_url: null,
  profile_completed: true,
  is_active: true,
  deactivation_reason: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const DEMO_ADMIN: Profile = {
  id: 'demo-admin-genril',
  role: 'admin',
  email: 'genriltheo@gmail.com',
  full_name: 'Genril Theo Sorono',
  first_name: 'Genril Theo',
  middle_initial: null,
  last_name: 'Sorono',
  suffix: null,
  course: null,
  year_level: null,
  university: null,
  age: null,
  gender: null,
  address: null,
  personal_email: null,
  contact_number: null,
  photo_url: null,
  skills: [],
  specializations: [],
  ai_skills: [],
  ai_specializations: [],
  resume_url: null,
  resume_status: null,
  resume_analyzed_at: null,
  resume_ai_suggestion: null,
  portfolio_link: null,
  portfolio_file_url: null,
  profile_completed: true,
  is_active: true,
  deactivation_reason: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
